AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: get_new_event_reply_from_email

Metadata:
  AWS::ServerlessRepo::Application:
    Name: get-new-event-reply-from-email
    Description: API application for the get_new_event_reply_from_email SAM app.
    Author: 31events
    # SpdxLicenseId: N/A
    # LicenseUrl: LICENSE.txt
    ReadmeUrl: ../README.md
    # SemanticVersion is ignored by the SAM publisher CodeBuild
    # instead version comes from the Git tag that triggers the CodeBuild.
    SemanticVersion: 0.0.1

  cfn-lint:
    config:
      ignore_checks:
        - W3002 # Because we're using Lambda Layers

Parameters:
  ############
  # Required #
  ############
  NewEventReplyTopicName:
    Type: String
    Description: Topic name of new event reply notification.

  GetNewEventReplyFromEmailQueueName:
    Type: String
    Description: Queue name of new event reply notification.

  S3BucketName:
    Type: String
    Description: S3 Bucket where incoming logs are stored.

  S3Prefix:
    Type: String
    Description: Prefix in S3 Bucket where incoming logs are stored.

  LayerVersionArn:
    Type: String
    Description: SharedLib Lambda Layer version ARN.

  ############
  # Optional #
  ############
  LogLevel:
    Type: String
    Description: Log level for lambda.
    Default: WARNING

  LogRetentionDays:
    Type: String
    Description: Number of days to retin logs before expiring them.
    AllowedValues:
      - "-1"
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
    Default: 180

Conditions:
  LogRetentionIsSet: !Not [!Equals [!Ref LogRetentionDays, "-1"]]

Resources:
  GetNewEventReplyFromEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/functions/get_new_event_reply_from_email/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt GetNewEventReplyFromEmailFunctionRole.Arn
      Timeout: 10 # TODO: Reduce this to 3s when this function can consistently achieve it.
      MemorySize: 1024
      Layers:
        - !Ref LayerVersionArn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            BatchSize: 1
            Enabled: True
            Queue: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${GetNewEventReplyFromEmailQueueName}
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          REGION: !Ref AWS::Region
          NEW_EVENT_REPLY: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${NewEventReplyTopicName}
          SQS_URL: !Sub https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${GetNewEventReplyFromEmailQueueName}

  GetNewEventReplyFromEmailFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CloudWatch
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - "sqs:DeleteMessage"
                  - "sqs:ReceiveMessage"
                  - "sqs:GetQueueAttributes"
                Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${GetNewEventReplyFromEmailQueueName}
              - Effect: Allow
                Action: "s3:GetObject"
                Resource: !Sub "arn:aws:s3:::${S3BucketName}/${S3Prefix}/*"
              - Effect: Allow
                Action:
                  - "sns:Publish"
                  - "sns:Subscribe"
                Resource: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${NewEventReplyTopicName}

  GetNewEventReplyFromEmailLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${GetNewEventReplyFromEmailFunction}"
      RetentionInDays: !If
        - LogRetentionIsSet
        - !Ref LogRetentionDays
        - !Ref AWS::NoValue

Outputs:
  #####################################
  # GetNewEventReplyFromEmailFunction #
  #####################################

  GetNewEventReplyFromEmailFunction:
    Description: GetNewEventReplyFromEmail Lambda Function ARN
    Value: !GetAtt GetNewEventReplyFromEmailFunction.Arn

  GetNewEventReplyFromEmailFunctionRole:
    Description: IAM Role for the GetNewEventReplyFromEmail function
    Value: !GetAtt GetNewEventReplyFromEmailFunctionRole.Arn

  GetNewEventReplyFromEmailLogGroup:
    Description: Log Group for the GetNewEventReplyFromEmail function.
    Value: !Ref GetNewEventReplyFromEmailLogGroup
