AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: stage_attendees_for_cancelled_event

Metadata:
  AWS::ServerlessRepo::Application:
    Name: stage-attendees-for-cancelled-event
    Description: API application for the stage_attendees_for_cancelled_event SAM app.
    Author: 31events
    # SpdxLicenseId: N/A
    # LicenseUrl: LICENSE.txt
    ReadmeUrl: ../README.md
    # SemanticVersion is ignored by the SAM publisher CodeBuild
    # instead version comes from the Git tag that triggers the CodeBuild.
    SemanticVersion: 0.0.1

  cfn-lint:
    config:
      ignore_checks:
        - W3002 # Because we're using Lambda Layers

Parameters:
  ############
  # Required #
  ############
  DynamoDbTableName:
    Type: String
    Description: Name of DynamoDb table to write to/read from.

  StageAttendeesForCancelledEventSnsTopicName:
    Type: String
    Description: Name of the Stage Attendees For Cancelled Event Completion SNS Topic to write to.

  StageAttendeesForCancelledEventSqsQueueName:
    Type: String
    Description: Name of the Stage Attendees For Cancelled Event SQS Queue to read from.

  LayerVersionArn:
    Type: String
    Description: SharedLib Lambda Layer version ARN.

  ############
  # Optional #
  ############
  LogLevel:
    Type: String
    Description: Log level for lambda.
    Default: WARNING

  LogRetentionDays:
    Type: String
    Description: Number of days to retin logs before expiring them.
    AllowedValues:
      - "-1"
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
      - 400
      - 545
      - 731
      - 1827
      - 3653
    Default: 180

Conditions:
  LogRetentionIsSet: !Not [!Equals [!Ref LogRetentionDays, "-1"]]

Resources:
  StageAttendeesForCancelledEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../src/functions/stage_attendees_for_cancelled_event/
      Handler: app.lambda_handler
      Runtime: python3.8
      Role: !GetAtt StageAttendeesForCancelledEventFunctionRole.Arn
      Timeout: 10 # TODO: Reduce this to 3s when this function can consistently achieve it.
      MemorySize: 1024
      Layers:
        - !Ref LayerVersionArn
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            BatchSize: 1
            Enabled: True
            Queue: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${StageAttendeesForCancelledEventSqsQueueName}
      Environment:
        Variables:
          LOG_LEVEL: !Ref LogLevel
          DYNAMODB_TABLE: !Ref DynamoDbTableName
          EVENT_CANCELLATION_REQUEST: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${StageAttendeesForCancelledEventSnsTopicName}
          REGION: !Ref AWS::Region
          SQS_URL: !Sub https://sqs.${AWS::Region}.amazonaws.com/${AWS::AccountId}/${StageAttendeesForCancelledEventSqsQueueName}

  StageAttendeesForCancelledEventFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service:
              - lambda.amazonaws.com
          Action: sts:AssumeRole
      Policies:
        - PolicyName: inline
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Sid: CloudWatch
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Sid: SqsWrite
                Effect: Allow
                Action:
                  - sqs:DeleteMessage
                  - sqs:ReceiveMessage
                  - sqs:GetQueueAttributes
                Resource: !Sub arn:aws:sqs:${AWS::Region}:${AWS::AccountId}:${StageAttendeesForCancelledEventSqsQueueName}
              - Sid: SnsWrite
                Effect: Allow
                Action:
                  - sns:Publish
                  - sns:Subscribe
                Resource: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${StageAttendeesForCancelledEventSnsTopicName}
              - Sid: DynamoDbRead
                Effect: Allow
                Action:
                  - dynamodb:DescribeTable
                  - dynamodb:GetItem
                  - dynamodb:Query
                Resource:
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDbTableName}
                  - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DynamoDbTableName}/index/*

  StageAttendeesForCancelledEventLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${StageAttendeesForCancelledEventFunction}"
      RetentionInDays: !If
        - LogRetentionIsSet
        - !Ref LogRetentionDays
        - !Ref AWS::NoValue

Outputs:
  #######################
  # StageAttendeesForCancelledEventFunction #
  #######################

  StageAttendeesForCancelledEventFunction:
    Description: "StageAttendeesForCancelledEvent Lambda Function ARN"
    Value: !GetAtt StageAttendeesForCancelledEventFunction.Arn

  StageAttendeesForCancelledEventFunctionRole:
    Description: "IAM Role for the StageAttendeesForCancelledEvent function"
    Value: !GetAtt StageAttendeesForCancelledEventFunctionRole.Arn

  StageAttendeesForCancelledEventLogGroup:
    Description: "Log Group for the StageAttendeesForCancelledEvent function."
    Value: !Ref StageAttendeesForCancelledEventLogGroup
